repos:

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.1.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-docstring-first
      -   id: check-json
      -   id: check-added-large-files
      -   id: check-yaml
      -   id: double-quote-string-fixer
