name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *' # Daily “At 00:00”
  workflow_dispatch: # allows you to trigger manually

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: python-${{ matrix.python-version }}
    if: github.repository == 'NCAR/ncar-jobqueue'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          micromamba-version: 'latest'
          environment-file: ci/environment.yml
          extra-specs: |
            python=${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          mamba-version: '*'
          activate-environment: ncar-jobqueue-dev
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}
          environment-file: ci/environment.yml

      - name: Install NCAR-jobqeueue
        run: |
          python -m pip install -e . --no-deps --force-reinstall
          conda list

      - name: Run Tests
        run: |
          python -m pytest

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
