name: Publish ncar-jobqueue to PyPI

on:
  release:
    types:
      - published
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    if: github.repository == 'NCAR/ncar-jobqueue'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          fetch-depth: 0
      - uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb
        name: Install Python
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools setuptools-scm wheel twine check-manifest
      - name: Build tarball and wheels
        run: |
          git clean -xdf
          git restore -SW .
          python -m build --sdist --wheel .
      - name: Check built artifacts
        run: |
          python -m twine check dist/*
          pwd
          if [ -f dist/ncar-jobqueue-0.0.0.tar.gz ]; then
            echo "❌ INVALID VERSION NUMBER"
            exit 1
          else
            echo "✅ Looks good"
          fi
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: releases
          path: dist

  test-built-dist:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb
        name: Install Python
        with:
          python-version: 3.9
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: releases
          path: dist
      - name: List contents of built dist
        run: |
          ls -ltrh
          ls -ltrh dist
  upload-to-pypi:
    needs: test-built-dist
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: releases
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          verbose: true
